---
title: "Bayesian Analysis"
output: html_notebook
author: "Ghislain d'Entremont"
---

# Load and Tidy Data

##### Load

```{r}
# load packages we'll use ----
library(tidyverse)
library(rstan)
rstan_options(auto_write = TRUE)

library(devtools)
install_github('mike-lawrence/ezStan')
library(ezStan)
```

##### Read 

```{r}
# Read in the data and look at it ----
dat = readr::read_csv('dat.csv')
View(dat)
```

##### Sort

```{r}
dat %>%
	dplyr::arrange(
		subj
	) -> dat
```

<!-- ##### Clean -->

<!-- ```{r} -->
<!-- dat[!complete.cases(dat),] -->
<!-- ``` -->

##### Within Contrasts

```{r}
W = get_contrast_matrix(
	data = dat
	, formula = ~  task * trial * laterality 
)
View(W)
```

##### Between Contrasts

I don't actually have any between-subject variables for the time being. 

```{r}
dat %>%
	dplyr::group_by(
		subj
	) %>%
	dplyr::summarize() %>% #View()
	get_contrast_matrix(
		formula = ~ 1
	) -> B
View(B)
```

# Sample

##### Run model and save

```{r}
post_c = rstan::stan(
	file = 'bayesian_analysis.stan'
	, data = list(
		nY = nrow(dat)
		, Y = dat$log_relative_power
		, nW = ncol(W)
		, W = W
		, nB = ncol(B)
		, B = B
		, nSubj = length(unique(dat$subj))
		, Subj = as.numeric(factor(dat$subj)) #ensures 1-nSubj
	)
	, seed = 1
	, chains = 4
	, cores = 4
	, iter = 1e3
)

save(
	post_c
	, file = 'post_c.rdata'
)
```

##### Examine posterior

```{r}
stan_summary(
	from_stan = post_c
	, par = 'coef_sds'
)
stan_summary(
	from_stan = post_c
	, par = 'coef_means'
)
stan_summary(
	from_stan = post_c
	, par = 'cor_mat'
)
```

